### ISSUE TITLE
Can't start sdt remotely

### ISSUE THREAD

**Issue by Gringo5000** [Prodiguer/synda#4] opened 2016-02-22 17:56 UTC
I commonly use a pdsh or rsh command to start init scripts on a remote host, especially when I need to operate on multiple nodes at once. When trying to start sdt remotely, however, the start command doesn't return. It appears to start the sdt daemon on the remote host, but the start command is hung and a ^C kills the sdt daemon on that remote host. Some basic printline debugging seems to imply sddaemon.py isn't getting called correctly as print statements in init aren't called.

**Comment by jripsl** [comment] 2016-02-22 18:37
I will try to reproduce the issue locally.
Can you provide os name, os version and synda installation method (source or system package) ?

**Comment by Gringo5000** [comment] 2016-02-22 18:48
OS=TOSS 2.4-6, which is based heavily on RHEL 6.7. I'm using the CentOS 6.7 RPM install of Synda.

**Comment by jripsl** [comment] 2016-02-22 22:14
Can you run the command below on the remote machine where synda is installed

```
sudo sed -i -e '\|/usr/share/python/synda/sdt/bin/sddaemon.py start|a \    sleep 1' /etc/init.d/sdt
```

then retry starting the daemon using remote shell

The problem seems that the daemonization process I use fails if the remote shell is closed too quickly.

**Comment by Gringo5000** [comment] 2016-02-22 22:22
The command returns with that extra sleep statement; however the daemon doesn't start.

**Comment by jripsl** [comment] 2016-02-22 22:29
Do command below work ?

ssh -c "sudo nohup service synda start"

Any error message in logfiles ?
(/var/log/synda/sdt/*)

**Comment by Gringo5000** [comment] 2016-02-22 23:05
My nodes aren't set up to be able to SSH to each other so I use rsh. Also SSH's -c option is to select a cipher, so I'm not sure if you're meaning to just run the sudo command or something else (assuming the former).

```
[root@aimsdtn5:~]# /etc/init.d/sdt status
Daemon not running
[root@aimsdtn5:~]# rsh e5 nohup service synda start
Starting synda daemon (sdt): 
[root@aimsdtn5:~]# /etc/init.d/sdt status
Daemon not running
```
I see the following in transfer.log:
```
2016-02-22 15:02:50,035 INFO SDDAEMON-001 Daemon starting ...
2016-02-22 15:02:50,035 INFO SDTSCHED-533 Connected to /var/lib/synda/sdt/sdt.db
2016-02-22 15:02:50,035 INFO SDTSCHED-993 Starting watchdog..
2016-02-22 15:02:50,356 ERROR SYDLOGON-040 Exception occured while retrieving certificate (status=4)
2016-02-22 15:02:50,357 ERROR SDTSCHED-920 Error occured while retrieving ESGF certificate
2016-02-22 15:02:50,357 INFO SDDAEMON-010 Exception occured (SYDLOGON-001)
2016-02-22 15:02:50,357 INFO SDDAEMON-034 Daemon stopped
```
... and this in stacktrace.log:
```
'sdlogon.sh' script returned an error
status=4
stdout=2016-02-22 15:02:50 - ERR009 - Error occured while retrieving certificate
stderr=
```

**Comment by jripsl** [comment] 2016-02-22 23:30
>  Also SSH's -c option is to select a cipher, 
>

Indeed, in fact I use "vagrant ssh" and I forgot to remove the "-c" option which doesn't have the same meaning when using ssh directly.
 
Ok, reading informations you provide, I think the daemon doesn't start because of a certificate problem.

Is openid configured in credentials.conf file on the remote host ?

Do the command below succeed on the remote host ?

`
synda certficate renew
`

Thanks

**Comment by Gringo5000** [comment] 2016-02-22 23:34
I saw that certificate error in the log after your last suggestion but wasn't sure what to do with it. Now running the cert renew command, I see it fails because I believe our ESGF data node is having problems. I notified the admin for that node earlier today and he is doing an update tomorrow that he hopes will fix some of the problems. Here's the renew output:
```
[root@aimsdtn5:~]# synda certificate renew
'sdlogon.sh' script returned an error

status=4
stdout=echo "St0reMyClim@te" | /usr/share/python/synda/sdt/bin/myproxyclient logon -T -b -S -s pcmdi.llnl.gov -p 7512 -l llnl_replication -o /var/tmp/synda/sdt/.esg/credentials.pem
2016-02-22 15:31:10 - ERR009 - Error occured while retrieving certificate
stderr=/usr/share/python/synda/sdt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/share/python/synda/sdt/bin/myproxyclient", line 9, in <module>
    load_entry_point('MyProxyClient==1.4.3', 'console_scripts', 'myproxyclient')()
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/script.py", line 196, in main
    do_logon(myproxy, options)      
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/script.py", line 220, in do_logon
    updateTrustRoots=options.trustroots)
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/client.py", line 1462, in logon
    conn.write('0')
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca'), ('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')]

Error occurs while renewing certificate (code=SYDLOGON-001,message=Cannot retrieve certificate from ESGF (hostname=pcmdi.llnl.gov,port=7512))
```

**Comment by jripsl** [comment] 2016-02-22 23:41
Ok, something seems wrong indeed with the certificate. 

> [root@aimsdtn5:~]# /etc/init.d/sdt status
> Daemon not running
> [root@aimsdtn5:~]# rsh e5 nohup service synda start
> Starting synda daemon (sdt): 
> [root@aimsdtn5:~]# /etc/init.d/sdt status
> Daemon not running
>
I see here that you are starting the *remote* daemon,
but checking the status of the *local* daemon.
Is this wanted ?
   

Thanks

**Comment by Gringo5000** [comment] 2016-02-22 23:43
Actually, it's the same node. I'm rsh-ing to itself to "remotely" start the daemon.

**Comment by jripsl** [comment] 2016-02-22 23:47
Okay, got it :)

So yes the problem is very likely caused by the certificate problem.

**Comment by jripsl** [comment] 2016-03-09 12:34
As cannot be reproduce for now, closed until new feedback from user.

**Comment by jripsl** [comment] 2016-03-09 12:34
As cannot be reproduce for now, closed until new feedback from user.

**Comment by Gringo5000** [comment] 2016-03-09 23:12
Jerome,
Sorry for the delay, but I'm not ready to close this. (I've either been unavailable or waiting for certificate updates.)

Currently, I'm failing to grab the certificate from my local index node and I have a couple questions. The data below warns about Python and SSL. Using the python packaged with Synda gives similar results. Should Python 2.6.6 still work? Any ideas on why the SSL handshake would fail?
Thanks

```
# synda certificate renew
'sdlogon.sh' script returned an error

status=4
stdout=echo XXXX | /usr/share/python/synda/sdt/bin/myproxyclient logon -T -b -S -s pcmdi.llnl.gov -p 7512 -l llnl_replication -o /var/tmp/synda/sdt/.esg/credentials.pem
2016-03-09 14:40:39 - ERR009 - Error occured while retrieving certificate
stderr=/usr/share/python/synda/sdt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/share/python/synda/sdt/bin/myproxyclient", line 9, in <module>
    load_entry_point('MyProxyClient==1.4.3', 'console_scripts', 'myproxyclient')()
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/script.py", line 196, in main
    do_logon(myproxy, options)
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/script.py", line 220, in do_logon
    updateTrustRoots=options.trustroots)
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/myproxy/client.py", line 1462, in logon
    conn.write('0')
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca'), ('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')]

Error occurs while renewing certificate (code=SYDLOGON-001,message=Cannot retrieve certificate from ESGF (hostname=pcmdi.llnl.gov,port=7512))

root@aimsdtn5:sdt]# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by jripsl** [comment] 2016-03-10 09:53
Reopened.

I am a bit stuck as I can't reproduce the ssl error.

I installed a new Centos 6.7 - 64bit  from scratch this morning:

* Synda 3.2 RPM for Centos 6.7
* Python 2.6.6
* OpenSSL 1.0.1e-fips 11 Feb 2013

So it seems exactly the same as you.

Then I ran

    synda certificate renew  

which complete successfully.

Can you retry after removing certificate folder, by running commands below:

    sudo rm -rf /var/tmp/synda/sdt/.esg
    sudo synda certificate renew

If it fails, maybe ask about the certificate error on the esgf-user@lists.llnl.gov mailing list,
as someone may already faced this issue.

**Comment by Gringo5000** [comment] 2016-03-10 22:22
Still no luck. I'll try posting to the list.

**Comment by Gringo5000** [comment] 2016-03-16 20:53
I wiped out the node and re-installed the OS and synda and synda works again - except for the issue represented by this ticket. Whether running with the init script patch or with nohup (actually, with both), the command still hangs every time. The only output I get is in the transfer.log file:
```
2016-03-16 13:48:38,391 INFO SDDAEMON-001 Daemon starting ...
2016-03-16 13:48:38,391 INFO SDTSCHED-533 Connected to /var/lib/synda/sdt/sdt.db
2016-03-16 13:48:38,391 INFO SDTSCHED-993 Starting watchdog..
2016-03-16 13:48:39,676 INFO SDTSCHED-902 Transfer daemon is now up and running
```

**Comment by Gringo5000** [comment] 2016-03-16 20:56
I ended up just putting an '&' at the end of the start command and it returns fine, so I'll just leave it at that. Thanks for looking into it.

**Comment by jripsl** [comment] 2016-03-17 07:09
Ok, I close the issue. 
Do not hesitate to reopen.

Thanks for your feedback.

**Closed by jripsl** 2016-03-17 07:09 UTC
